### ISSUE TITLE
Handling paths

### ISSUE THREAD

**Issue by oss6** [oss6/statico#10]
Handling paths properly using py or pathlib

**Comment by prologic** [comment]
I'd say play with both for a bit and see which one you like better :) I've used both! pathlib is part of Python 3's std lib and there is a backported version of it on PyPi. So up to you :)

**Comment by prologic** [comment]
Either/Or will make handling paths a lot easier though in a nice OOP way!

**Comment by oss6** [comment]
Yep understood. :)
