### ISSUE TITLE
AppServer should rebuild in a subprocess

### ISSUE THREAD

**Issue by prologic** [oss6/statico#12]
Because the regeneration of pages/articles is CPU bound the AppServer should regenerate the content in a subprocess. Currently it doesn't do this so there's a slight pause until it will serve requests again :) Easy fix though!

**Comment by oss6** [comment]
Yes seems very reasonable, I also changed open(f) to f.open() since we're using pathlib

**Comment by prologic** [comment]
Yes I saw that! Keep refactoring all the file/path handling; good work :)
