### ISSUE TITLE
Got a demo or example sites?

### ISSUE THREAD

**Issue by prologic** [oss6/statico#2]

**Comment by oss6** [comment]
Hi, I am making the website for the project on GitHub pages. Soon it will be available on https://oss6.github.io/statico.

**Comment by prologic** [comment]
Lovely :) With Bootstrap3?

**Comment by oss6** [comment]
No, with predefined themes provided by GitHub

**Comment by prologic** [comment]
Ahh that'll be interesting.

**Comment by prologic** [comment]
Need this ASAP so we can determine if we've broken anything important :) Even if what you've done so far is unfinished. I think the "files" should be part of this repo tiself too so it's easy to rebuild and test as statico is being developed :)

**Comment by oss6** [comment]
Here [https://oss6.github.io/statico](https://oss6.github.io/statico) I added a quick example.
> I think the "files" should be part of this repo tiself too so it's easy to rebuild and test as statico is being developed
Can you explain this part? Which "files"?

**Comment by prologic** [comment]
Sorry the files that created that site using statico :)

**Comment by oss6** [comment]
Now the statico website itself is made using statico. If more examples are needed just reopen this issue

**Comment by prologic** [comment]
Cool :+1:
