### ISSUE TITLE
Features for v0.0.2

### ISSUE THREAD

**Issue by oss6** [oss6/statico#3]
- [x] Comments, via an external service (Disqus).
- [x] Atom/RSS feeds
- [x] Import from RSS feeds
- [x] Isolate and integrate articles for fast rebuilding times
- [x] Automatic deployment to GitHub Pages using --deploy
- [x] Real-Time Web Server for previews #11 
- [x] Pygments support

**Comment by prologic** [comment]
This will only support Markdown right?

**Comment by prologic** [comment]
Do we want a builtin server to quickly test what you've written/etc?

**Comment by oss6** [comment]
I am thinking to support reStructuredText (or one can just put html directly). Yeah it would be awesome if you could contribute to it - I consider myself a beginner (I need guidance :D)

**Comment by prologic** [comment]
I'll add in a little web server for you that supports real time rendering/rebuilding if the sources change. Can you open a new issue for this and I'll work on a feature branch?

**Comment by oss6** [comment]
Yeah awesome!
