### ISSUE TITLE
Real time rendering/rebuilding

### ISSUE THREAD

**Issue by oss6** [oss6/statico#4]
Support for real time rendering/rebuilding when the sources change.

**Comment by prologic** [comment]
Would you like to try out my [server](https://github.com/prologic/statico/tree/server) branch and see what you think so far?

```
#!bash
git clone git@github.com:prologic/statico.git
git checkout server
pip install -r requirements.txt
python setup.py develop
statico
statico -g
statico -P
```

**Comment by oss6** [comment]
Brilliant! I love it! I also must make a change to the 'get all filenames' part in the generate function. It seems like it's repeating the relative path twice (i.e. content/articles/content/articles/...)

**Comment by prologic** [comment]
Cool glad you like it; it's not finished yet. A couple of questions:

* Do we care to support Windows/OS X?

**Comment by prologic** [comment]
wrt repeated code and handling paths; I'd highly recommend either [py](https://pypi.python.org/pypi/py) or [pathlib](https://pypi.python.org/pathlib) (*ehteir os*) -- Open a new issue though :)

**Comment by oss6** [comment]
Yeah I would like to support Window and OS X. Are there major differences in the built-in functions or is there a library for handling cross-platform functions?

**Comment by prologic** [comment]
Well I was *planning* on using [circuits](https://github.com/circuits/circuits) here; but it only support Linux (*at this time*) for real-time file system notifications. On BSD/OS-X you have to use the ``kqueue`` syscall9s) and on Windows you have to resort to "threading" (*There are ``win32`` APIs but you don't want to go there!*).

**Comment by prologic** [comment]
I'd say; get this working first one one platform; then we can worry about the others later :)

**Comment by oss6** [comment]
Yeah I agree. I am working on pathlib and py now.

**Comment by prologic** [comment]
No problems! Let me finish this off then :)

**Comment by prologic** [comment]
Okay prologic/statico@ce4662f50b adds the real-time features to the app server. But I'm running into a problem with your ``generate()`` function. I don't see any changes I make to ``content/index.md`` for example or a new article page. Any ideas?

**Comment by oss6** [comment]
Ah ok, index.md is intended for a custom index page. The default index page is the list of  articles (paginated). Have you tried to add an article and change it?

**Comment by prologic** [comment]
Yeap :)

**Comment by oss6** [comment]
I don't know what's the problem because if I update it manually it works fine (gets copied properly in output). I pushed some changes, I think it should work now (there was a problem with the paths)

**Comment by prologic** [comment]
Some bugs :) I fixed em!
