### ISSUE TITLE
Python 2/3 compatibility?

### ISSUE THREAD

**Issue by prologic** [oss6/statico#6]
I notice you list [six](https://pypi.pytholn.org/pypi/six) as a dependency. Are we wanting statico to be Python 2/3 compatible?

**Comment by oss6** [comment]
I just want it to be Python 3 compatible. I think six was installed with another package and I forgot to delete it. What do you think? Should we make it also compatible for Python 2?

**Comment by prologic** [comment]
Yes I think so; because a *LOT* of users still use and rely on Python 2 and some of us (*developers*) have to continue to support Python 2.6+ for example ([circuits](https://github.com/circuits/circuits))

**Comment by prologic** [comment]
So that being said; use the functionality of ``six`` so we can have a single codebase that works on both versions of Python. It's not really that difficult either :) Have a read through: [six docs](http://six.readthedocs.org/)

**Comment by oss6** [comment]
Ah ok, understood :)

**Comment by prologic** [comment]
If you're okay with this; I will write/contribute my code to [statico](https://github.com/oss6/statico/issues) to be Python 2/3 compatible and fix things as I go along :)

**Comment by oss6** [comment]
I am absolutely ok! :D

**Comment by prologic** [comment]
Okay then leave [this issue](https://github.com/oss6/statico/issues/6) open until statico works on both Python 2 and 3 :) We'll have to do some testing and fix up a few things!
