### ISSUE TITLE
PEP8 compliance and code style?

### ISSUE THREAD

**Issue by prologic** [oss6/statico#7]
Are you familiar with [PEP8](https://www.python.org/dev/peps/pep-0008/) Do you like clean, readable and nicely styled code?

See also this nice Github integration tool: [Landscape](https://landscape.io)

**Comment by oss6** [comment]
I work with IDE PyCharm and most of the PEP8 guidelines popup when are not respected. Yeah, I think the code needs cleaning, reformatting and more comments

**Comment by oss6** [comment]
Thanks for Landscape, I will give it a try

**Comment by prologic** [comment]
Great! Then you won't mind if I runt he codebase through [autopep8](https://pypi.python.org/pypi/autopep8)? I'll submit a [Pull Request](https://github.com/oss6/statico/pulls) shortly :)

**Comment by prologic** [comment]
I really like Landscape :) I use it on my proejct!

**Comment by oss6** [comment]
Yeah it's absolutely ok for me! Thanks for all these tools, I will learn more about them and use them.

**Comment by prologic** [comment]
No worries! PR coming!
